server.port=8081

# Docker-compose service names will be: inventory, notification
inventory.baseUrl=${INVENTORY_URL:http://localhost:8082}
notification.baseUrl=${NOTIFICATION_URL:http://localhost:8083}

